set up travis automation on jekyll branch

diff --git a/travis/push b/travis/push
--- a/travis/push
+++ b/travis/push
@@ -1,20 +1,16 @@
 #!/usr/bin/env bash
 
-SOURCE_BRANCH="jekyll"
-TARGET_BRANCH="gh-pages"
+# Exit with nonzero exit code if anything fails.
+set -e
 
-# Save some useful information
-REPO=`git config remote.origin.url`
-SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
-SHA=`git rev-parse --verify HEAD`
+cd $TRAVIS_BUILD_DIR
+source travis/config
+source travis/decrypt
+cd $GIT_TARGET_FOLDER
 
-# Now let's go have some fun with the cloned repo
-cd output
-ls -lah
-git config user.name "Travis CI"
-# git config user.email "$COMMIT_AUTHOR_EMAIL"
-git config user.email "paolo.brasolin@gmail.com"
-# git config user.name "Paolo Brasolin"
+git config user.name "$GIT_USER_NAME"
+git config user.email "$GIT_USER_EMAIL"
+git config push.default simple
 
 # If there are no changes to the compiled out (e.g. this is a README update) then just bail.
 # if [ -z `git diff --exit-code` ]; then
@@ -22,14 +18,7 @@ git config user.email "paolo.brasolin@gmail.com"
     # exit 0
 # fi
 
-# Commit the "changes", i.e. the new version.
-# The delta will show diffs between new and old versions.
-git status
 git add -A
-git status
-git commit -m "Deploy to GitHub Pages: ${SHA}"
-git status
-# git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
+git commit -m "Travis #$TRAVIS_BUILD_NUMBER"
+git push git@github.com:$TRAVIS_REPO_SLUG.git $TARGET_BRANCH
 
-# Now that we're all set up, we can push.
-git push $SSH_REPO $TARGET_BRANCH
